services:
  josafa:
    build:
      context: .
      dockerfile: ./docker/uv/Dockerfile
    container_name: josafa
    depends_on:
      mongodb:
        condition: service_started
      kokoro:
        condition: service_started
    environment:
      BOT_DEFAULT_PREFIX: ${BOT_DEFAULT_PREFIX}
      BOT_DISCORD_TOKEN: ${BOT_DISCORD_TOKEN}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_HOST: mongodb
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: josafa_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGODB_INIT_DATABASE: ${MONGODB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - josafa_mongodb_data:/data/db
    restart: unless-stopped

volumes:
  josafa_mongodb_data:
