services:
  mongodb:
    image: mongo:latest
    container_name: josafa_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGODB_INIT_DATABASE: ${MONGODB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - josafa_mongodb_data:/data/db

volumes:
  josafa_mongodb_data:
